package utils

const MAX_STAT_ALGO = 10

const (
	ONEDAY      = 1
	ONEWEEK     = 7
	FIFTEENDAYS = 15
	ONEMONTH    = 30
	TWOMONTHS   = 60
	THREEMONTHS = 90
	SIXMONTH    = 180
	ONEYEAR     = 365
	TWOYEARS    = 730
	THREEYEARS  = 1095
)

const (
	ONEDAYIDX      = 1
	ONEWEEKIDX     = 2
	FIFTEENDAYSIDX = 3
	ONEMONTHIDX    = 4
	TWOMONTHSIDX   = 5
	THREEMONTHSIDX = 6
	SIXMONTHIDX    = 7
	ONEYEARIDX     = 8
	TWOYEARSIDX    = 9
	THREEYEARSIDX  = 10
)
